version: '2'

services:
  imsep_postgis:
    container_name: imsep_postgis
    restart: unless-stopped
    image: kartoza/postgis:11.0-2.5 
#    ports: 
#      - "127.0.0.1:25432:5432"
    volumes:  
      - /data/imsep/db_data:/var/lib/postgresql/11/main  
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASS: post1msep
      POSTGIS_GDAL_ENABLED_DRIVERS: ENABLE_ALL
  pgbackups:
        container_name: imsep_pgbackups
        image: prodrigestivill/postgres-backup-local
        restart: unless-stopped
        volumes:
            #- /var/opt/pgbackups:/backups
            #- pgbackups:/backups
            - /data/imsep/backups:/backups
            #- c:/docker/backups:/backups
        links:
            - imsep_postgis
        depends_on:
            - imsep_postgis
            - imsep
        environment:
            - POSTGRES_HOST=imsep_postgis
            - POSTGRES_DB=imsep,imsep_gdb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=post1msep
            - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
            - SCHEDULE=@daily
            - BACKUP_KEEP_DAYS=7
            - BACKUP_KEEP_WEEKS=4
            - BACKUP_KEEP_MONTHS=6
            - HEALTHCHECK_PORT=1337
  imsep:
    container_name: imsep
    restart: unless-stopped
    image: imsep
    build: .
    depends_on:
      - imsep_postgis
    links:
      - imsep_postgis
    environment:
      NODE_ENV: production
      DB_HOSTNAME: imsep_postgis 
      DB_PORT: 5432
      DB_PASSWORD: post1msep
      GDB_HOSTNAME: imsep_postgis
      GDB_PORT: 5432
      GDB_PASSWORD: post1msep
      DB_REBUILD: 'false'
    ports:
      - "127.0.0.1:1336:1337"   
    volumes:
      - /data/imsep/log:/usr/src/app/log
      - /data/imsep/app_data:/usr/src/app/app_data   
volumes:
  postgis:
  imsep:
  pgbackups:
    