version: '2'

services:
  imsep_postgis:
    container_name: imsep_postgis
    restart: unless-stopped
    image: kartoza/postgis:latest 
    ports: 
      - "25432:5432"
    volumes:  
      #- imsepdb:/var/lib/postgresql/data  
       #- imsepdb:/var/lib/postgresql/data
      #- c:\docker\imsep\db_data:/var/lib/postgresql/11/main  
      - imsepdb:/var/lib/postgresql/11/main  
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASS: d747db4520c046ccb5db14f39a014746
      POSTGIS_GDAL_ENABLED_DRIVERS: ENABLE_ALL

  imsep:
    container_name: imsep_debug
    restart: unless-stopped
    image: imsep
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - imsep_postgis
    links:
      - imsep_postgis
    environment:
      NODE_ENV: development
      DB_HOSTNAME: imsep_postgis 
      DB_PORT: 5432
      DB_PASSWORD: d747db4520c046ccb5db14f39a014746
      GDB_HOSTNAME: imsep_postgis
      GDB_PORT: 5432
      GDB_PASSWORD: d747db4520c046ccb5db14f39a014746
      DB_REBUILD: 'false'
    ports:
      - "1338:1337"
      - "9229:9229"  
    command: node --inspect=0.0.0.0:9229 server    
    volumes:
      - ./controllers:/usr/src/app/controllers
      - ./models:/usr/src/app/models
      - ./scripts:/usr/src/app/scripts
      - ./public:/usr/src/app/public
      - ./views:/usr/src/app/views
      - ./log:/usr/src/app/log
      - ./app_data:/usr/src/app/app_data   
      - ./app_data/uploads:/usr/src/app/app_data/uploads
      
volumes:
  imsepdb:
    