version: '2'

services:
  imsep_postgis:
    container_name: imsep_postgis
    restart: unless-stopped
    #image: kartoza/postgis:11.0-2.5
    image: mdillon/postgis:latest
    #ports: 
    #  - "25432:5432"
    volumes:  
      #- imsepdb:/var/lib/postgresql/data
      #- c:\docker\imsep\db_data:/var/lib/postgresql/11/main  
      #- imsepdb:/var/lib/postgresql/data  
      #- c:\docker\imsep\db_data:/var/lib/postgresql/11/main
      - imsepdb:/var/lib/postgresql/11/main 
      - imsepdb_mdillon:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASS: d747db4520c046ccb5db14f39a014746
      POSTGRES_PASSWORD: d747db4520c046ccb5db14f39a014746
      
      POSTGIS_GDAL_ENABLED_DRIVERS: ENABLE_ALL
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready -U postgres"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5  
      
  pgbackups:
        container_name: imsep_pgbackups
        image: prodrigestivill/postgres-backup-local
        restart: unless-stopped
        volumes:
            #- /var/opt/pgbackups:/backups
            #- pgbackups:/backups
            - c:/docker/imsep/backups:/backups
        links:
            - imsep_postgis
        depends_on:
            - imsep_postgis
            - imsep
        environment:
            - POSTGRES_HOST=imsep_postgis
            - POSTGRES_DB=imsep,imsep_gdb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=d747db4520c046ccb5db14f39a014746
            - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
            - SCHEDULE=@daily
            - BACKUP_KEEP_DAYS=7
            - BACKUP_KEEP_WEEKS=4
            - BACKUP_KEEP_MONTHS=6
            - HEALTHCHECK_PORT=1337
            
  imsep:
    container_name: imsep
    restart: unless-stopped
    image: imsep
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - imsep_postgis
      #imsep_postgis:
      #  condition: service_healthy
    links:
      - imsep_postgis
    environment:
      NODE_ENV: production
      APP_HOST: http://192.168.1.2:1336
      DB_HOSTNAME: imsep_postgis 
      DB_PORT: 5432
      DB_PASSWORD: d747db4520c046ccb5db14f39a014746
      GDB_HOSTNAME: imsep_postgis
      GDB_PORT: 5432
      GDB_PASSWORD: d747db4520c046ccb5db14f39a014746
      DB_REBUILD: 'false'
    ports:
      - "1336:1337"   
    volumes:
      #- ./log:/usr/src/app/log
      - c:\docker\imsep\log:/usr/src/app/log
      #- ./app_data:/usr/src/app/app_data   
      - c:\docker\imsep\app_data:/usr/src/app/app_data
      
volumes:
  imsepdb:
  imsepdb_mdillon:
  pgbackups:
    