version: '2'

services:
  imsep_postgis_test:
    container_name: imsep_postgis
    restart: unless-stopped
    image: mdillon/postgis:11
#    ports: 
#      - "127.0.0.1:25432:5432"
    # volumes:  
      # - /data/imsep/db_data:/var/lib/postgresql/data  
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASS: d747db4520c046ccb5db14f39a014746
      POSTGRES_PASSWORD: d747db4520c046ccb5db14f39a014746
      POSTGIS_GDAL_ENABLED_DRIVERS: ENABLE_ALL  
  imsep_test:
    container_name: imsep
    restart: unless-stopped
    image: imsep
    build: .
    depends_on:
      - imsep_postgis
    links:
      - imsep_postgis
    environment:
      NODE_ENV: production
      APP_HOST: https://imsep.gis.lu.se
      DB_HOSTNAME: imsep_postgis 
      DB_PORT: 5432
      DB_PASSWORD: d747db4520c046ccb5db14f39a014746
      GDB_HOSTNAME: imsep_postgis
      GDB_PORT: 5432
      GDB_PASSWORD: d747db4520c046ccb5db14f39a014746
      DB_REBUILD: 'false'
    ports:
      - "127.0.0.1:3336:1337"   
    # volumes:
    #   - /data/imsep/log:/usr/src/app/log
    #   - /data/imsep/app_data:/usr/src/app/app_data   
volumes:
  postgis:
  imsep:
  pgbackups:  