version: '2.1'

services:
  postgis:
    restart: unless-stopped
    image: kartoza/postgis:latest 
    ports: 
      - "25432:5432"
    volumes:  
      - db-data:/var/lib/postgresql/data  
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASS: d747db4520c046ccb5db14f39a014746
      POSTGIS_GDAL_ENABLED_DRIVERS: ENABLE_ALL

  imsep:
    restart: unless-stopped
    image: imsep
    build: .
    depends_on:
      - postgis
    links:
      - postgis
    environment:
      NODE_ENV: production
      DB_HOSTNAME: postgis 
      DB_PORT: 5432
      DB_PASSWORD: d747db4520c046ccb5db14f39a014746
      GDB_HOSTNAME: postgis
      GDB_PORT: 5432
      GDB_PASSWORD: d747db4520c046ccb5db14f39a014746
      DB_REBUILD: 'false'
      DB_SEED: 'false'
    ports:
      - "1336:1337"   
    volumes:
      - ./log:/usr/src/app/log
      - ./uploads:/usr/src/app/uploads   
      
volumes:
  db-data:
    